### ISSUE TITLE
grunt build-production fails

### ISSUE THREAD

**Issue by IslandUsurper** [Mozu/core-theme#81]
If you try to run the build production task . . .
```
$ grunt build-production
Running "jshint:production" (jshint) task
>> 60 files lint free.

Running "mozutheme:fullcompile" (mozutheme) task
Verifying property mozutheme.fullcompile exists in config...ERROR
>> Unable to process task.
Warning: Required config property "mozutheme.fullcompile" missing. Use --force to continue.

Aborted due to warnings.
```
In Gruntfile.js, the `mozutheme` config section has "compile", not "fullcompile".

**Comment by Amjcraft** [comment]
What branch are you using? Both our master and develop branches have a "fullcompile" task under mozutheme -> fullcompile.

**Comment by IslandUsurper** [comment]
@Amjcraft, whichever one `yo mozu-theme` sets up. I'm not sure how I can tell, but maybe the problem is there.

**Comment by IslandUsurper** [comment]
This is a problem should be fixed by Mozu/generator-mozu-theme#3.

**Comment by sudhirdhumal289** [comment]
Problem still exists. Just created new folder and executed yo mozu-theme and tried to execute the build-production grunt task but giving an error mentioned above in issue description.
